# Generated by Django 5.0.6 on 2024-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
