# Generated by Django 5.0.6 on 2024-07-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_stripe_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_checkout_id',
        ),
    ]
