# Generated by Django 5.0.6 on 2024-06-28 21:13

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('أسيا', 'أسيا'), ('أفريقيا', 'أفريقيا'), ('أمريكا', 'أمريكا'), ('أوروبا', 'أوروبا')], max_length=50)),
                ('photo', models.ImageField(upload_to=home.models.image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('continent', models.CharField(choices=[('أسيا', 'أسيا'), ('أفريقيا', 'أفريقيا'), ('أمريكا', 'أمريكا'), ('أوروبا', 'أوروبا')], max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=home.models.image_upload)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=30)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Egypt', 'Egypt'), ('Cairo International Airport', 'Cairo International Airport')], max_length=50)),
                ('date', models.DateField()),
                ('flight_class', models.CharField(choices=[('FirstClass', 'FirstClass'), ('BusnissClass', 'BusnissClass'), ('PremiumClass', 'PremiumClass'), ('EconomyClass', 'EconomyClass')], max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_id', models.CharField(max_length=100)),
                ('payment_bool', models.BooleanField(default=False)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
