# Generated by Django 5.0.6 on 2024-05-10 22:00

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('continent', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=home.models.image_upload)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
