# Generated by Django 5.0.6 on 2024-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_place_delete_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('America', 'America'), ('Europe', 'Europe')], max_length=30),
        ),
    ]
