# Generated by Django 5.0.6 on 2024-06-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser'),
        ('home', '0002_userpayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser'),
        ),
    ]
