# Generated by Django 5.0.6 on 2024-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_place_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
