# Generated by Django 5.0.6 on 2024-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userpayment_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
