# Generated by Django 5.0.6 on 2024-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_place_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='period',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Years', 'Years')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
