# Generated by Django 5.0.6 on 2024-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_place_duration_place_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='period',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=30),
        ),
    ]
