# Generated by Django 5.0.6 on 2024-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='crete_id',
            field=models.IntegerField(default=1),
        ),
    ]
