# Generated by Django 5.0.6 on 2024-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_place_crete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='crete_id',
            field=models.IntegerField(default=1),
        ),
    ]
