# Generated by Django 5.0.6 on 2024-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('America', 'America'), ('Europe', 'Europe')], max_length=50),
        ),
    ]
