# Generated by Django 5.0.6 on 2024-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_continent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='flight_class',
            field=models.CharField(choices=[('FirstClass', 'FirstClass'), ('BusnissClass', 'BusnissClass'), ('PremiumClass', 'PremiumClass'), ('EconomyClass', 'EconomyClass')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='source',
            field=models.CharField(choices=[('Egypt', 'Egypt'), ('Cairo International Airport', 'Cairo International Airport')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
