# Generated by Django 5.0.6 on 2024-06-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_place_date_place_flight_class_place_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(),
        ),
    ]
