# Generated by Django 5.0.6 on 2024-06-21 22:05

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_place_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='photo',
            field=models.ImageField(default=1, upload_to=home.models.image_upload),
            preserve_default=False,
        ),
    ]
