# Generated by Django 5.0.6 on 2024-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_continent_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='crete_id',
        ),
    ]
