# Generated by Django 5.0.6 on 2024-05-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='accompanying1',
            new_name='features1',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='accompanying2',
            new_name='features2',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='accompanying3',
            new_name='features3',
        ),
    ]
