# Generated by Django 5.0.6 on 2024-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_accompanying1_hotel_features1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
