# Generated by Django 5.0.6 on 2024-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='crete_id',
            field=models.IntegerField(default=1),
        ),
    ]
