# Generated by Django 5.0.6 on 2024-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_hotel_crete_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='crete_id',
        ),
    ]
